/**
 * The script a pooled machine runs to become useful.
 *
 * Served by the relay at `/api/environment/pool-bootstrap.sh` and fetched by
 * the sprite, rather than pushed into it. Exec takes no usable stdin, so the
 * only thing that fits down that channel is a URL — and a script that arrives
 * over HTTPS from the relay is also a script that can be fixed without
 * rebuilding a shelf of machines.
 *
 * It contains NO secrets. The two arguments it takes are the machine's own name
 * and a per-row token whose entire power is "mark this one row ready"; the
 * device token that actually matters arrives later, over TLS, when somebody
 * claims the machine.
 *
 * ## It runs as a service, and that is load-bearing
 *
 * A paused sprite keeps its filesystem and loses every process. Sprite services
 * "persist across reboots" and "restart automatically on boot", so the same
 * script is what runs after a wake — which is why every step is guarded and
 * idempotent, and why the tail of it waits rather than exits.
 */

export interface PoolBootstrapOptions {
  /** Where the machine reports readiness and fetches its identity. https://… */
  relayHttpUrl: string;
  /** Repository to fall back to when no Linux build is published yet. */
  sourceRepo?: string;
}

const APT_PACKAGES = [
  // A display server, because Electron brings up the GTK/X stack during startup
  // whether or not a window is ever shown.
  "xvfb", "xauth",
  // Chromium's runtime libraries. A missing one of these is not a warning, it
  // is `error while loading shared libraries` and exit 127.
  "libgtk-3-0", "libnotify4", "libnss3", "libxss1", "libxtst6", "xdg-utils",
  "libatspi2.0-0", "libdrm2", "libgbm1", "libxcb-dri3-0",
  "libcups2t64", "libasound2t64",
  "libxcomposite1", "libxdamage1", "libxfixes3", "libxrandr2",
  "libpango-1.0-0", "libcairo2", "libglib2.0-0",
  // FUSE, so an AppImage can mount itself. Without it the download is inert and
  // the fallback path is the only one that ever runs.
  "libfuse2t64",
];

/**
 * Build the script.
 *
 * A function rather than a file so the relay URL is baked in at serve time: the
 * machine has no configuration of its own, and a script that has to be told
 * where to phone home is a script with one more thing to get wrong.
 */
export function poolBootstrapScript(opts: PoolBootstrapOptions): string {
  const relay = opts.relayHttpUrl.replace(/\/+$/, "");
  const repo = opts.sourceRepo ?? "https://github.com/phuryn/grok-build-vscode.git";

  return `#!/usr/bin/env bash
# Generated by the relay. Do not edit in place — it is refetched on rebuild.
set -uo pipefail

NAME="\${1:-}"
SECRET="\${2:-}"
RELAY="${relay}"
APP="$HOME/afkpilot"
STAMP="$APP/.afkpilot-installed"
ENVFILE="$HOME/.afkpilot.env"
LOG="$HOME/afkpilot-boot.log"
exec >>"$LOG" 2>&1
step() { echo "[$(date -Is)] $* (t+\${SECONDS}s)"; }

# The name and secret are needed once, on the first boot, to report readiness.
# Every later boot is a wake, and by then this file is what identifies us.
if [ -n "$NAME" ] && [ -n "$SECRET" ]; then
  umask 077
  printf '%s\\n%s\\n' "$NAME" "$SECRET" > "$HOME/.afkpilot-pool"
fi

AGENTS_STAMP="$HOME/.afkpilot-agents-updated"
AGENT_MAX_AGE=604800   # a week

# Install or refresh the agent CLIs. Each is independent and non-fatal.
install_agents() {
  step "agents: installing/updating"
  curl -fsSL https://x.ai/cli/install.sh | bash >/dev/null 2>&1 || step "grok CLI install FAILED"
  curl -fsSL https://claude.ai/install.sh | bash >/dev/null 2>&1 || step "claude CLI install FAILED"
  npm install -g @openai/codex@latest >/dev/null 2>&1 || step "codex CLI install FAILED"
}

# Keep them current, because nobody else will.
#
# On a laptop the person installed these and owns updating them. In a cloud
# environment nobody did, so left alone they rot until an agent stops working
# against its own service and the reader has no idea why.
#
# BEFORE the host starts, never while it runs: replacing a CLI binary underneath
# a turn in flight breaks a live session, which is a worse failure than being a
# few days behind. And at most weekly, so waking a machine you use daily is not
# a download every time.
refresh_agents_if_stale() {
  [ -f "$ENVFILE" ] || return 0          # unclaimed: the build already did it
  local last=0
  [ -f "$AGENTS_STAMP" ] && last=$(cat "$AGENTS_STAMP" 2>/dev/null || echo 0)
  local now; now=$(date +%s)
  [ $((now - last)) -lt "$AGENT_MAX_AGE" ] && return 0
  install_agents
  date +%s > "$AGENTS_STAMP"
}

HOST_STAMP="$APP/.afkpilot-host-checked"
ASSET_RECORD="$APP/.afkpilot-asset"

# Keep the HOST current too, for the same reason as the CLIs and with a sharper
# edge: the install was one-shot, so a machine took whatever build existed on
# the day it was made and kept it for ever. Nobody can walk up to a cloud
# machine and press update, so a fix shipped here would never reach anybody
# already using one — which is the same outcome as never shipping it.
#
# NON-DESTRUCTIVE, unlike the first install. The new build is unpacked BESIDE
# the running one and swapped in only once its AppRun exists; anything short of
# that leaves the machine exactly as it was. A cloud environment that fails to
# update is a machine a week behind. One that deletes its own host is a machine
# somebody has lost.
#
# Same timing rule as the CLIs: at boot, before the host starts, never while a
# turn is in flight.
refresh_host_if_stale() {
  [ -f "$ENVFILE" ] || return 0          # unclaimed: the build already did it
  [ "$(cat "$APP/.afkpilot-kind" 2>/dev/null)" = "appimage" ] || return 0
  local last=0
  [ -f "$HOST_STAMP" ] && last=$(cat "$HOST_STAMP" 2>/dev/null || echo 0)
  local now; now=$(date +%s)
  [ $((now - last)) -lt "$AGENT_MAX_AGE" ] && return 0
  # Stamped BEFORE the work: a release whose asset cannot be fetched must not
  # make every wake for the rest of the week retry the whole download.
  date +%s > "$HOST_STAMP"

  local asset
  asset=$(curl -fsSL --max-time 60 https://api.github.com/repos/phuryn/grok-build-vscode/releases/latest \\
    | grep -o '"browser_download_url": *"[^"]*\\.AppImage"' \\
    | head -1 | sed 's/.*"\\(https[^"]*\\)"/\\1/')
  [ -n "\${asset:-}" ] || { step "host update: no published build found"; return 0; }
  # The URL carries the version, so an unchanged one means there is nothing to
  # do — and finding that out costs one small request instead of 110 MB.
  [ "$asset" = "$(cat "$ASSET_RECORD" 2>/dev/null)" ] && return 0

  step "host update: fetching $asset"
  rm -rf "$APP/next"; mkdir -p "$APP/next" || return 0
  if ! curl -fL "$asset" -o "$APP/next/afkpilot.AppImage" \\
      --retry 4 --retry-delay 5 --retry-all-errors --continue-at - \\
      --speed-limit 51200 --speed-time 60 --max-time 180 --silent --show-error; then
    # BOUNDED at three minutes, unlike the first install. This runs on a wake,
    # with somebody very likely waiting for the machine to answer — and the host
    # does not start until it returns. The resume flag keeps whatever it got, so
    # a slow link finishes the update across a few boots rather than holding one
    # of them open for a quarter of an hour.
    step "host update: download did not finish in time; keeping the build we have"
    rm -rf "$APP/next"; return 0
  fi
  chmod +x "$APP/next/afkpilot.AppImage"
  if ! (cd "$APP/next" && ./afkpilot.AppImage --appimage-extract >/dev/null 2>&1) \\
     || [ ! -x "$APP/next/squashfs-root/AppRun" ]; then
    step "host update: did not unpack; keeping the build we have"
    rm -rf "$APP/next"; return 0
  fi

  # The swap. Only now is the running build touched at all.
  rm -rf "$APP/squashfs-root.old"
  mv "$APP/squashfs-root" "$APP/squashfs-root.old" 2>/dev/null || true
  if mv "$APP/next/squashfs-root" "$APP/squashfs-root"; then
    mv "$APP/next/afkpilot.AppImage" "$APP/afkpilot.AppImage" 2>/dev/null || true
    printf '%s\\n' "$asset" > "$ASSET_RECORD"
    rm -rf "$APP/next" "$APP/squashfs-root.old"
    step "host update: installed"
  else
    # Put it back. A machine with no host is worse than a stale one.
    mv "$APP/squashfs-root.old" "$APP/squashfs-root" 2>/dev/null || true
    rm -rf "$APP/next"
    step "host update: swap failed; kept the build we have"
  fi
}

# FETCH THIS SCRIPT AGAIN, FIRST, AND RE-EXEC.
#
# The service runs a COPY of this file that was written the day the machine was
# built. Without this, everything below — including the host updater — is frozen
# at whatever shipped then, and a machine nobody can walk up to can never
# receive a fix. Shipping one would be the same as not shipping it.
#
# Syntax-checked before it replaces anything, so a truncated download
# cannot leave a machine that will not boot. Guarded by an environment variable
# so the re-exec happens at most once, and failure is a no-op: the copy we
# already have is a working script.
if [ -z "\${AFKPILOT_BOOT_REFRESHED:-}" ]; then
  export AFKPILOT_BOOT_REFRESHED=1
  NEXT="$HOME/.afkpilot-boot.next"
  if curl -fsSL --max-time 30 "$RELAY/api/environment/pool-bootstrap.sh" -o "$NEXT" \\
     && [ -s "$NEXT" ] && sh -n "$NEXT" 2>/dev/null; then
    if ! cmp -s "$NEXT" "$HOME/afkpilot-boot.sh"; then
      mv "$NEXT" "$HOME/afkpilot-boot.sh"
      chmod +x "$HOME/afkpilot-boot.sh"
      step "boot script updated; re-running it"
      exec "$HOME/afkpilot-boot.sh" "$@"
    fi
  fi
  rm -f "$NEXT"
fi

step "boot"

if [ ! -f "$STAMP" ]; then
  step "install: apt"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \\
    ${APT_PACKAGES.join(" ")} || { step "apt FAILED"; exit 71; }

  # Preferred: a published Linux build. Downloading 110 MB and unpacking it is
  # seconds; building the same thing from source was measured at 25 minutes,
  # nearly all of it npm ci thrashing the VM's writable overlay.
  # Matched on the EXTENSION alone, not on an architecture string.
  # electron-builder names AppImages "-linux-x86_64.AppImage", not "-linux-x64"
  # like every other target — and a pattern that assumed otherwise matched
  # nothing, silently fell through to the source build, and cost 25 minutes per
  # machine while looking like it was working as designed. There is only ever
  # one AppImage in a release, so the extension is the whole identity needed.
  step "install: looking for a published Linux build"
  ASSET=$(curl -fsSL https://api.github.com/repos/phuryn/grok-build-vscode/releases/latest \\
    | grep -o '"browser_download_url": *"[^"]*\\.AppImage"' \\
    | head -1 | sed 's/.*"\\(https[^"]*\\)"/\\1/')

  if [ -n "\${ASSET:-}" ]; then
    rm -rf "$APP"; mkdir -p "$APP"

    # Jitter before a 110 MB download.
    #
    # The filler starts a whole shelf at once, so without this every machine
    # asks GitHub for the same large file in the same second. Measured
    # 2026-08-27: ten simultaneous builds, five stuck mid-download and marked
    # failed an hour later. A few seconds of spread costs nothing on a shelf
    # being filled ahead of demand.
    sleep $(( (RANDOM % 25) + 1 ))

    step "install: downloading $ASSET"
    # --retry with resume, and a CEILING. A stalled download used to hang until
    # the stale sweep gave up 60 minutes later; --speed-limit turns "stopped
    # making progress" into a retry rather than a machine that is neither
    # working nor failed.
    curl -fL "$ASSET" -o "$APP/afkpilot.AppImage" \\
      --retry 4 --retry-delay 5 --retry-all-errors --continue-at - \\
      --speed-limit 51200 --speed-time 60 --max-time 900 \\
      --silent --show-error 2>>"$LOG"

    if [ -s "$APP/afkpilot.AppImage" ]; then
      chmod +x "$APP/afkpilot.AppImage"
      # Extracted rather than run directly: --appimage-extract needs no FUSE at
      # runtime, so a kernel without it does not turn into a machine that
      # installed cleanly and cannot start.
      if (cd "$APP" && ./afkpilot.AppImage --appimage-extract >/dev/null 2>&1) \\
         && [ -x "$APP/squashfs-root/AppRun" ]; then
        echo appimage > "$APP/.afkpilot-kind"
        # What we installed, so a later refresh can tell "already current" from
        # "never checked" without downloading 110 MB to find out.
        printf '%s\\n' "$ASSET" > "$APP/.afkpilot-asset"
        date +%s > "$APP/.afkpilot-host-checked"
        step "install: unpacked"
      else
        # A truncated or corrupt download extracts to nothing. Say so, and let
        # the source build below produce a working machine rather than leaving
        # a half-installed one that reports ready and cannot start.
        step "install: AppImage did not unpack; discarding it"
        rm -rf "$APP/squashfs-root" "$APP/afkpilot.AppImage"
      fi
    else
      step "install: download produced nothing"
    fi
  fi

  # Fallback: build it. Slow, and correct — this is what runs until a Linux
  # build is published, and what keeps working if a release is ever missing one.
  if [ ! -f "$APP/.afkpilot-kind" ]; then
    step "install: no published build; building from source"
    rm -rf "$APP"
    git clone --quiet --depth 1 ${repo} "$APP" || { step "clone FAILED"; exit 72; }
    cd "$APP" || exit 73
    npm ci --no-audit --no-fund --silent || { step "npm ci FAILED"; exit 74; }
    # electron's postinstall has been observed to leave a broken dist after a
    # successful \`npm ci\`, which then fails at startup with "Electron failed to
    # install correctly". Running it again is cheap and makes the difference
    # between a machine that works and one that boots into a stack trace.
    node node_modules/electron/install.js >/dev/null 2>&1 || true
    npm run compile --silent || { step "compile FAILED"; exit 75; }
    echo source > "$APP/.afkpilot-kind"
  fi

  # ALL THREE agent CLIs, explicitly.
  #
  # Fly's base image happens to ship claude and codex, and not grok. Relying on
  # that is relying on somebody else's image to keep containing what we need:
  # the day it drops one, machines quietly come up an agent short and the only
  # symptom is a user being told to install something on a computer that does
  # not exist. Installing all three costs seconds and makes it ours.
  #
  # Non-fatal, each: two agents out of three is a usable machine, and the client
  # already renders "not installed" honestly. What is NOT acceptable is being
  # unable to tell afterwards, so the result is logged either way.
  install_agents
  for a in grok claude codex; do
    if command -v "$a" >/dev/null 2>&1; then step "agent present: $a"; else step "agent MISSING: $a"; fi
  done
  date +%s > "$AGENTS_STAMP"

  touch "$STAMP"
  step "install: done"
fi

# Report readiness — once, and only while we are still unclaimed. A machine that
# has already been given to somebody must never go back on the shelf.
if [ -f "$HOME/.afkpilot-pool" ] && [ ! -f "$ENVFILE" ]; then
  NAME=$(sed -n 1p "$HOME/.afkpilot-pool")
  SECRET=$(sed -n 2p "$HOME/.afkpilot-pool")
  step "reporting ready as $NAME"
  curl -fsS -X POST -H 'content-type: application/json' \\
    -d "{\\"name\\":\\"$NAME\\",\\"secret\\":\\"$SECRET\\"}" \\
    "$RELAY/api/environment/pool/ready" >/dev/null \\
    || step "readiness report failed; a later boot will retry"
fi

# Wait to be claimed. The claim writes this file and restarts the service, so
# this loop is for the case where the restart raced the write, and for a machine
# that boots while still on the shelf.
while [ ! -f "$ENVFILE" ]; do sleep 5; done

set -a; . "$ENVFILE"; set +a
refresh_agents_if_stale
refresh_host_if_stale
cd "$APP" || exit 73

pkill -f "Xvfb :99" 2>/dev/null || true
Xvfb :99 -screen 0 1280x900x24 -nolisten tcp -ac >/tmp/xvfb.log 2>&1 &
export DISPLAY=:99
export DBUS_SESSION_BUS_ADDRESS=/dev/null
for _ in $(seq 1 50); do [ -e /tmp/.X11-unix/X99 ] && break; sleep 0.2; done
[ -e /tmp/.X11-unix/X99 ] || { step "Xvfb failed"; cat /tmp/xvfb.log; exit 69; }

step "display up; starting host"
if [ "$(cat "$APP/.afkpilot-kind" 2>/dev/null)" = "appimage" ]; then
  # APPDIR, explicitly. AppRun derives it from $0 when it is unset, and for an
  # EXTRACTED AppImage exec'd from a service that derivation came out empty --
  # so BIN resolved to "/grok-build-desktop", the host never started, and the
  # only trace was one line in a log nobody was reading. The machine installed
  # perfectly and then did nothing, which is the worst shape a failure can take.
  export APPDIR="$APP/squashfs-root"
  exec "$APPDIR/AppRun" --no-sandbox
fi
exec node scripts/run-desktop.cjs --relay-dev --no-sandbox
`;
}

/**
 * The command that puts a fresh sprite to work.
 *
 * Fetch the script, then register it as a SERVICE rather than running it here.
 * Two reasons, and the second is the one that matters: an exec's child has no
 * supervisor and dies with the connection, and a 25-minute install held open on
 * a WebSocket is a 25-minute opportunity for a network to blink. A service
 * survives both, and is restarted on every boot — which is the only reason a
 * machine paused for a week comes back on its own.
 */
export function poolBuildCommand(input: {
  relayHttpUrl: string;
  /**
   * The shelf row to report against, when there is one.
   *
   * Omitted for a machine built TO ORDER — somebody opened their cloud
   * environment while the shelf was empty, so it belongs to them from the
   * moment it exists and there is no readiness to report. The script skips its
   * report when it has no name and secret, which is what makes one script serve
   * both paths; two scripts would be two things to keep in step, and the
   * on-demand one would be the one nobody exercised.
   */
  name?: string;
  claimSecret?: string;
}): string[] {
  const relay = input.relayHttpUrl.replace(/\/+$/, "");
  const pooled = input.name && input.claimSecret;
  const script = [
    `curl -fsSL ${relay}/api/environment/pool-bootstrap.sh -o "$HOME/afkpilot-boot.sh"`,
    `chmod +x "$HOME/afkpilot-boot.sh"`,
    `/.sprite/bin/sprite-env services create afkpilot`
      + ` --cmd "$HOME/afkpilot-boot.sh"`
      + (pooled ? ` --args '${input.name},${input.claimSecret}'` : "")
      + ` --no-stream`,
  ].join(" && ");
  return ["sh", "-c", script];
}
