/**
 * The script a pooled machine runs to become useful.
 *
 * Served by the relay at `/api/environment/pool-bootstrap.sh` and fetched by
 * the sprite, rather than pushed into it. Exec takes no usable stdin, so the
 * only thing that fits down that channel is a URL — and a script that arrives
 * over HTTPS from the relay is also a script that can be fixed without
 * rebuilding a shelf of machines.
 *
 * It contains NO secrets. The two arguments it takes are the machine's own name
 * and a per-row token whose entire power is "mark this one row ready"; the
 * device token that actually matters arrives later, over TLS, when somebody
 * claims the machine.
 *
 * ## It runs as a service, and that is load-bearing
 *
 * A paused sprite keeps its filesystem and loses every process. Sprite services
 * "persist across reboots" and "restart automatically on boot", so the same
 * script is what runs after a wake — which is why every step is guarded and
 * idempotent, and why the tail of it waits rather than exits.
 */

export interface PoolBootstrapOptions {
  /** Where the machine reports readiness and fetches its identity. https://… */
  relayHttpUrl: string;
  /** Repository to fall back to when no Linux build is published yet. */
  sourceRepo?: string;
}

const APT_PACKAGES = [
  // A display server, because Electron brings up the GTK/X stack during startup
  // whether or not a window is ever shown.
  "xvfb", "xauth",
  // Chromium's runtime libraries. A missing one of these is not a warning, it
  // is `error while loading shared libraries` and exit 127.
  "libgtk-3-0", "libnotify4", "libnss3", "libxss1", "libxtst6", "xdg-utils",
  "libatspi2.0-0", "libdrm2", "libgbm1", "libxcb-dri3-0",
  "libcups2t64", "libasound2t64",
  "libxcomposite1", "libxdamage1", "libxfixes3", "libxrandr2",
  "libpango-1.0-0", "libcairo2", "libglib2.0-0",
  // FUSE, so an AppImage can mount itself. Without it the download is inert and
  // the fallback path is the only one that ever runs.
  "libfuse2t64",
];

/**
 * Build the script.
 *
 * A function rather than a file so the relay URL is baked in at serve time: the
 * machine has no configuration of its own, and a script that has to be told
 * where to phone home is a script with one more thing to get wrong.
 */
export function poolBootstrapScript(opts: PoolBootstrapOptions): string {
  const relay = opts.relayHttpUrl.replace(/\/+$/, "");
  const repo = opts.sourceRepo ?? "https://github.com/phuryn/grok-build-vscode.git";

  return `#!/usr/bin/env bash
# Generated by the relay. Do not edit in place — it is refetched on rebuild.
set -uo pipefail

NAME="\${1:-}"
SECRET="\${2:-}"
RELAY="${relay}"
APP="$HOME/afkpilot"
STAMP="$APP/.afkpilot-installed"
ENVFILE="$HOME/.afkpilot.env"
LOG="$HOME/afkpilot-boot.log"
exec >>"$LOG" 2>&1
step() { echo "[$(date -Is)] $* (t+\${SECONDS}s)"; }

# The name and secret are needed once, on the first boot, to report readiness.
# Every later boot is a wake, and by then this file is what identifies us.
if [ -n "$NAME" ] && [ -n "$SECRET" ]; then
  umask 077
  printf '%s\\n%s\\n' "$NAME" "$SECRET" > "$HOME/.afkpilot-pool"
fi

step "boot"

if [ ! -f "$STAMP" ]; then
  step "install: apt"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \\
    ${APT_PACKAGES.join(" ")} || { step "apt FAILED"; exit 71; }

  # Preferred: a published Linux build. Downloading 110 MB and unpacking it is
  # seconds; building the same thing from source was measured at 25 minutes,
  # nearly all of it npm ci thrashing the VM's writable overlay.
  # Matched on the EXTENSION alone, not on an architecture string.
  # electron-builder names AppImages "-linux-x86_64.AppImage", not "-linux-x64"
  # like every other target — and a pattern that assumed otherwise matched
  # nothing, silently fell through to the source build, and cost 25 minutes per
  # machine while looking like it was working as designed. There is only ever
  # one AppImage in a release, so the extension is the whole identity needed.
  step "install: looking for a published Linux build"
  ASSET=$(curl -fsSL https://api.github.com/repos/phuryn/grok-build-vscode/releases/latest \\
    | grep -o '"browser_download_url": *"[^"]*\\.AppImage"' \\
    | head -1 | sed 's/.*"\\(https[^"]*\\)"/\\1/')

  if [ -n "\${ASSET:-}" ]; then
    step "install: downloading $ASSET"
    rm -rf "$APP"; mkdir -p "$APP"
    if curl -fsSL "$ASSET" -o "$APP/afkpilot.AppImage"; then
      chmod +x "$APP/afkpilot.AppImage"
      # Extracted rather than run directly: --appimage-extract needs no FUSE at
      # runtime, so a kernel without it does not turn into a machine that
      # installed cleanly and cannot start.
      (cd "$APP" && ./afkpilot.AppImage --appimage-extract >/dev/null 2>&1) \\
        && echo appimage > "$APP/.afkpilot-kind"
    fi
  fi

  # Fallback: build it. Slow, and correct — this is what runs until a Linux
  # build is published, and what keeps working if a release is ever missing one.
  if [ ! -f "$APP/.afkpilot-kind" ]; then
    step "install: no published build; building from source"
    rm -rf "$APP"
    git clone --quiet --depth 1 ${repo} "$APP" || { step "clone FAILED"; exit 72; }
    cd "$APP" || exit 73
    npm ci --no-audit --no-fund --silent || { step "npm ci FAILED"; exit 74; }
    # electron's postinstall has been observed to leave a broken dist after a
    # successful \`npm ci\`, which then fails at startup with "Electron failed to
    # install correctly". Running it again is cheap and makes the difference
    # between a machine that works and one that boots into a stack trace.
    node node_modules/electron/install.js >/dev/null 2>&1 || true
    npm run compile --silent || { step "compile FAILED"; exit 75; }
    echo source > "$APP/.afkpilot-kind"
  fi

  touch "$STAMP"
  step "install: done"
fi

# Report readiness — once, and only while we are still unclaimed. A machine that
# has already been given to somebody must never go back on the shelf.
if [ -f "$HOME/.afkpilot-pool" ] && [ ! -f "$ENVFILE" ]; then
  NAME=$(sed -n 1p "$HOME/.afkpilot-pool")
  SECRET=$(sed -n 2p "$HOME/.afkpilot-pool")
  step "reporting ready as $NAME"
  curl -fsS -X POST -H 'content-type: application/json' \\
    -d "{\\"name\\":\\"$NAME\\",\\"secret\\":\\"$SECRET\\"}" \\
    "$RELAY/api/environment/pool/ready" >/dev/null \\
    || step "readiness report failed; a later boot will retry"
fi

# Wait to be claimed. The claim writes this file and restarts the service, so
# this loop is for the case where the restart raced the write, and for a machine
# that boots while still on the shelf.
while [ ! -f "$ENVFILE" ]; do sleep 5; done

set -a; . "$ENVFILE"; set +a
cd "$APP" || exit 73

pkill -f "Xvfb :99" 2>/dev/null || true
Xvfb :99 -screen 0 1280x900x24 -nolisten tcp -ac >/tmp/xvfb.log 2>&1 &
export DISPLAY=:99
export DBUS_SESSION_BUS_ADDRESS=/dev/null
for _ in $(seq 1 50); do [ -e /tmp/.X11-unix/X99 ] && break; sleep 0.2; done
[ -e /tmp/.X11-unix/X99 ] || { step "Xvfb failed"; cat /tmp/xvfb.log; exit 69; }

step "display up; starting host"
if [ "$(cat "$APP/.afkpilot-kind" 2>/dev/null)" = "appimage" ]; then
  # APPDIR, explicitly. AppRun derives it from $0 when it is unset, and for an
  # EXTRACTED AppImage exec'd from a service that derivation came out empty --
  # so BIN resolved to "/grok-build-desktop", the host never started, and the
  # only trace was one line in a log nobody was reading. The machine installed
  # perfectly and then did nothing, which is the worst shape a failure can take.
  export APPDIR="$APP/squashfs-root"
  exec "$APPDIR/AppRun" --no-sandbox
fi
exec node scripts/run-desktop.cjs --relay-dev --no-sandbox
`;
}

/**
 * The command that puts a fresh sprite to work.
 *
 * Fetch the script, then register it as a SERVICE rather than running it here.
 * Two reasons, and the second is the one that matters: an exec's child has no
 * supervisor and dies with the connection, and a 25-minute install held open on
 * a WebSocket is a 25-minute opportunity for a network to blink. A service
 * survives both, and is restarted on every boot — which is the only reason a
 * machine paused for a week comes back on its own.
 */
export function poolBuildCommand(input: {
  relayHttpUrl: string;
  /**
   * The shelf row to report against, when there is one.
   *
   * Omitted for a machine built TO ORDER — somebody opened their cloud
   * environment while the shelf was empty, so it belongs to them from the
   * moment it exists and there is no readiness to report. The script skips its
   * report when it has no name and secret, which is what makes one script serve
   * both paths; two scripts would be two things to keep in step, and the
   * on-demand one would be the one nobody exercised.
   */
  name?: string;
  claimSecret?: string;
}): string[] {
  const relay = input.relayHttpUrl.replace(/\/+$/, "");
  const pooled = input.name && input.claimSecret;
  const script = [
    `curl -fsSL ${relay}/api/environment/pool-bootstrap.sh -o "$HOME/afkpilot-boot.sh"`,
    `chmod +x "$HOME/afkpilot-boot.sh"`,
    `/.sprite/bin/sprite-env services create afkpilot`
      + ` --cmd "$HOME/afkpilot-boot.sh"`
      + (pooled ? ` --args '${input.name},${input.claimSecret}'` : "")
      + ` --no-stream`,
  ].join(" && ");
  return ["sh", "-c", script];
}
